export interface CountryData {
    name: string;
    ibfSupported: boolean;
    initialZoom: number;
}

export const countries: Map<string, CountryData> = new Map([
    ["AFG", { name: "Afghanistan", ibfSupported: false, initialZoom: 10 }],
    ["ALB", { name: "Albania", ibfSupported: false, initialZoom: 10 }],
    ["DZA", { name: "Algeria", ibfSupported: false, initialZoom: 10 }],
    ["AND", { name: "Andorra", ibfSupported: false, initialZoom: 10 }],
    ["AGO", { name: "Angola", ibfSupported: false, initialZoom: 10 }],
    ["ATG", { name: "Antigua and Barbuda", ibfSupported: false, initialZoom: 10 }],
    ["ARG", { name: "Argentina", ibfSupported: false, initialZoom: 10 }],
    ["ARM", { name: "Armenia", ibfSupported: false, initialZoom: 10 }],
    ["AUS", { name: "Australia", ibfSupported: false, initialZoom: 10 }],
    ["AUT", { name: "Austria", ibfSupported: false, initialZoom: 10 }],
    ["AZE", { name: "Azerbaijan", ibfSupported: false, initialZoom: 10 }],
    ["BHS", { name: "Bahamas", ibfSupported: false, initialZoom: 10 }],
    ["BHR", { name: "Bahrain", ibfSupported: false, initialZoom: 10 }],
    ["BGD", { name: "Bangladesh", ibfSupported: false, initialZoom: 10 }],
    ["BRB", { name: "Barbados", ibfSupported: false, initialZoom: 10 }],
    ["BLR", { name: "Belarus", ibfSupported: false, initialZoom: 10 }],
    ["BEL", { name: "Belgium", ibfSupported: false, initialZoom: 10 }],
    ["BLZ", { name: "Belize", ibfSupported: false, initialZoom: 10 }],
    ["BEN", { name: "Benin", ibfSupported: false, initialZoom: 10 }],
    ["BTN", { name: "Bhutan", ibfSupported: false, initialZoom: 10 }],
    ["BOL", { name: "Bolivia", ibfSupported: false, initialZoom: 10 }],
    ["BIH", { name: "Bosnia and Herzegovina", ibfSupported: false, initialZoom: 10 }],
    ["BWA", { name: "Botswana", ibfSupported: false, initialZoom: 10 }],
    ["BRA", { name: "Brazil", ibfSupported: false, initialZoom: 10 }],
    ["BRN", { name: "Brunei", ibfSupported: false, initialZoom: 10 }],
    ["BGR", { name: "Bulgaria", ibfSupported: false, initialZoom: 10 }],
    ["BFA", { name: "Burkina Faso", ibfSupported: false, initialZoom: 10 }],
    ["BDI", { name: "Burundi", ibfSupported: false, initialZoom: 10 }],
    ["CPV", { name: "Cabo Verde", ibfSupported: false, initialZoom: 10 }],
    ["KHM", { name: "Cambodia", ibfSupported: false, initialZoom: 10 }],
    ["CMR", { name: "Cameroon", ibfSupported: false, initialZoom: 10 }],
    ["CAN", { name: "Canada", ibfSupported: false, initialZoom: 10 }],
    ["CAF", { name: "Central African Republic", ibfSupported: false, initialZoom: 10 }],
    ["TCD", { name: "Chad", ibfSupported: false, initialZoom: 10 }],
    ["CHL", { name: "Chile", ibfSupported: false, initialZoom: 10 }],
    ["CHN", { name: "China", ibfSupported: false, initialZoom: 10 }],
    ["COL", { name: "Colombia", ibfSupported: true, initialZoom: 10 }],
    ["COM", { name: "Comoros", ibfSupported: false, initialZoom: 10 }],
    ["COG", { name: "Congo", ibfSupported: false, initialZoom: 10 }],
    ["COD", { name: "Congo (Democratic Republic)", ibfSupported: false, initialZoom: 10 }],
    ["CRI", { name: "Costa Rica", ibfSupported: false, initialZoom: 10 }],
    ["CIV", { name: "Côte d'Ivoire", ibfSupported: false, initialZoom: 10 }],
    ["HRV", { name: "Croatia", ibfSupported: false, initialZoom: 10 }],
    ["CUB", { name: "Cuba", ibfSupported: false, initialZoom: 10 }],
    ["CYP", { name: "Cyprus", ibfSupported: false, initialZoom: 10 }],
    ["CZE", { name: "Czechia", ibfSupported: false, initialZoom: 10 }],
    ["DNK", { name: "Denmark", ibfSupported: false, initialZoom: 10 }],
    ["DJI", { name: "Djibouti", ibfSupported: false, initialZoom: 10 }],
    ["DMA", { name: "Dominica", ibfSupported: false, initialZoom: 10 }],
    ["DOM", { name: "Dominican Republic", ibfSupported: false, initialZoom: 10 }],
    ["ECU", { name: "Ecuador", ibfSupported: false, initialZoom: 10 }],
    ["EGY", { name: "Egypt", ibfSupported: false, initialZoom: 10 }],
    ["SLV", { name: "El Salvador", ibfSupported: false, initialZoom: 10 }],
    ["GNQ", { name: "Equatorial Guinea", ibfSupported: false, initialZoom: 10 }],
    ["ERI", { name: "Eritrea", ibfSupported: false, initialZoom: 10 }],
    ["EST", { name: "Estonia", ibfSupported: false, initialZoom: 10 }],
    ["SWZ", { name: "Eswatini", ibfSupported: false, initialZoom: 10 }],
    ["ETH", { name: "Ethiopia", ibfSupported: true, initialZoom: 10 }],
    ["FJI", { name: "Fiji", ibfSupported: false, initialZoom: 10 }],
    ["FIN", { name: "Finland", ibfSupported: false, initialZoom: 10 }],
    ["FRA", { name: "France", ibfSupported: false, initialZoom: 10 }],
    ["GAB", { name: "Gabon", ibfSupported: false, initialZoom: 10 }],
    ["GMB", { name: "Gambia", ibfSupported: false, initialZoom: 10 }],
    ["GEO", { name: "Georgia", ibfSupported: false, initialZoom: 10 }],
    ["DEU", { name: "Germany", ibfSupported: false, initialZoom: 10 }],
    ["GHA", { name: "Ghana", ibfSupported: false, initialZoom: 10 }],
    ["GRC", { name: "Greece", ibfSupported: false, initialZoom: 10 }],
    ["GRD", { name: "Grenada", ibfSupported: false, initialZoom: 10 }],
    ["GTM", { name: "Guatemala", ibfSupported: false, initialZoom: 10 }],
    ["GIN", { name: "Guinea", ibfSupported: false, initialZoom: 10 }],
    ["GNB", { name: "Guinea-Bissau", ibfSupported: false, initialZoom: 10 }],
    ["GUY", { name: "Guyana", ibfSupported: false, initialZoom: 10 }],
    ["HTI", { name: "Haiti", ibfSupported: false, initialZoom: 10 }],
    ["HND", { name: "Honduras", ibfSupported: false, initialZoom: 10 }],
    ["HUN", { name: "Hungary", ibfSupported: false, initialZoom: 10 }],
    ["ISL", { name: "Iceland", ibfSupported: false, initialZoom: 10 }],
    ["IND", { name: "India", ibfSupported: false, initialZoom: 10 }],
    ["IDN", { name: "Indonesia", ibfSupported: false, initialZoom: 10 }],
    ["IRN", { name: "Iran", ibfSupported: false, initialZoom: 10 }],
    ["IRQ", { name: "Iraq", ibfSupported: false, initialZoom: 10 }],
    ["IRL", { name: "Ireland", ibfSupported: false, initialZoom: 10 }],
    ["ISR", { name: "Israel", ibfSupported: false, initialZoom: 10 }],
    ["ITA", { name: "Italy", ibfSupported: false, initialZoom: 10 }],
    ["JAM", { name: "Jamaica", ibfSupported: false, initialZoom: 10 }],
    ["JPN", { name: "Japan", ibfSupported: false, initialZoom: 10 }],
    ["JOR", { name: "Jordan", ibfSupported: false, initialZoom: 10 }],
    ["KAZ", { name: "Kazakhstan", ibfSupported: false, initialZoom: 10 }],
    ["KEN", { name: "Kenya", ibfSupported: true, initialZoom: 10 }],
    ["KIR", { name: "Kiribati", ibfSupported: false, initialZoom: 10 }],
    ["PRK", { name: "Korea (North)", ibfSupported: false, initialZoom: 10 }],
    ["KOR", { name: "Korea (South)", ibfSupported: false, initialZoom: 10 }],
    ["KWT", { name: "Kuwait", ibfSupported: false, initialZoom: 10 }],
    ["KGZ", { name: "Kyrgyzstan", ibfSupported: false, initialZoom: 10 }],
    ["LAO", { name: "Laos", ibfSupported: false, initialZoom: 10 }],
    ["LVA", { name: "Latvia", ibfSupported: false, initialZoom: 10 }],
    ["LBN", { name: "Lebanon", ibfSupported: false, initialZoom: 10 }],
    ["LSO", { name: "Lesotho", ibfSupported: false, initialZoom: 10 }],
    ["LBR", { name: "Liberia", ibfSupported: false, initialZoom: 10 }],
    ["LBY", { name: "Libya", ibfSupported: false, initialZoom: 10 }],
    ["LIE", { name: "Liechtenstein", ibfSupported: false, initialZoom: 10 }],
    ["LTU", { name: "Lithuania", ibfSupported: false, initialZoom: 10 }],
    ["LUX", { name: "Luxembourg", ibfSupported: false, initialZoom: 10 }],
    ["MDG", { name: "Madagascar", ibfSupported: false, initialZoom: 10 }],
    ["MWI", { name: "Malawi", ibfSupported: true, initialZoom: 10 }],
    ["MYS", { name: "Malaysia", ibfSupported: false, initialZoom: 10 }],
    ["MDV", { name: "Maldives", ibfSupported: false, initialZoom: 10 }],
    ["MLI", { name: "Mali", ibfSupported: false, initialZoom: 10 }],
    ["MLT", { name: "Malta", ibfSupported: false, initialZoom: 10 }],
    ["MHL", { name: "Marshall Islands", ibfSupported: false, initialZoom: 10 }],
    ["MRT", { name: "Mauritania", ibfSupported: false, initialZoom: 10 }],
    ["MUS", { name: "Mauritius", ibfSupported: false, initialZoom: 10 }],
    ["MEX", { name: "Mexico", ibfSupported: false, initialZoom: 10 }],
    ["FSM", { name: "Micronesia", ibfSupported: false, initialZoom: 10 }],
    ["MDA", { name: "Moldova", ibfSupported: false, initialZoom: 10 }],
    ["MCO", { name: "Monaco", ibfSupported: false, initialZoom: 10 }],
    ["MNG", { name: "Mongolia", ibfSupported: false, initialZoom: 10 }],
    ["MNE", { name: "Montenegro", ibfSupported: false, initialZoom: 10 }],
    ["MAR", { name: "Morocco", ibfSupported: false, initialZoom: 10 }],
    ["MOZ", { name: "Mozambique", ibfSupported: false, initialZoom: 10 }],
    ["MMR", { name: "Myanmar", ibfSupported: false, initialZoom: 10 }],
    ["NAM", { name: "Namibia", ibfSupported: false, initialZoom: 10 }],
    ["NRU", { name: "Nauru", ibfSupported: false, initialZoom: 10 }],
    ["NPL", { name: "Nepal", ibfSupported: false, initialZoom: 10 }],
    ["NLD", { name: "Netherlands", ibfSupported: false, initialZoom: 10 }],
    ["NZL", { name: "New Zealand", ibfSupported: false, initialZoom: 10 }],
    ["NIC", { name: "Nicaragua", ibfSupported: false, initialZoom: 10 }],
    ["NER", { name: "Niger", ibfSupported: false, initialZoom: 10 }],
    ["NGA", { name: "Nigeria", ibfSupported: false, initialZoom: 10 }],
    ["MKD", { name: "North Macedonia", ibfSupported: false, initialZoom: 10 }],
    ["NOR", { name: "Norway", ibfSupported: false, initialZoom: 10 }],
    ["OMN", { name: "Oman", ibfSupported: false, initialZoom: 10 }],
    ["PAK", { name: "Pakistan", ibfSupported: false, initialZoom: 10 }],
    ["PLW", { name: "Palau", ibfSupported: false, initialZoom: 10 }],
    ["PAN", { name: "Panama", ibfSupported: false, initialZoom: 10 }],
    ["PNG", { name: "Papua New Guinea", ibfSupported: false, initialZoom: 10 }],
    ["PRY", { name: "Paraguay", ibfSupported: false, initialZoom: 10 }],
    ["PER", { name: "Peru", ibfSupported: false, initialZoom: 10 }],
    ["PHL", { name: "Philippines", ibfSupported: true, initialZoom: 10 }],
    ["POL", { name: "Poland", ibfSupported: false, initialZoom: 10 }],
    ["PRT", { name: "Portugal", ibfSupported: false, initialZoom: 10 }],
    ["QAT", { name: "Qatar", ibfSupported: false, initialZoom: 10 }],
    ["ROU", { name: "Romania", ibfSupported: false, initialZoom: 10 }],
    ["RUS", { name: "Russia", ibfSupported: false, initialZoom: 10 }],
    ["RWA", { name: "Rwanda", ibfSupported: false, initialZoom: 10 }],
    ["KNA", { name: "Saint Kitts and Nevis", ibfSupported: false, initialZoom: 10 }],
    ["LCA", { name: "Saint Lucia", ibfSupported: false, initialZoom: 10 }],
    ["VCT", { name: "Saint Vincent and the Grenadines", ibfSupported: false, initialZoom: 10 }],
    ["WSM", { name: "Samoa", ibfSupported: false, initialZoom: 10 }],
    ["SMR", { name: "San Marino", ibfSupported: false, initialZoom: 10 }],
    ["STP", { name: "Sao Tome and Principe", ibfSupported: false, initialZoom: 10 }],
    ["SAU", { name: "Saudi Arabia", ibfSupported: false, initialZoom: 10 }],
    ["SEN", { name: "Senegal", ibfSupported: false, initialZoom: 10 }],
    ["SRB", { name: "Serbia", ibfSupported: false, initialZoom: 10 }],
    ["SYC", { name: "Seychelles", ibfSupported: false, initialZoom: 10 }],
    ["SLE", { name: "Sierra Leone", ibfSupported: false, initialZoom: 10 }],
    ["SGP", { name: "Singapore", ibfSupported: false, initialZoom: 10 }],
    ["SVK", { name: "Slovakia", ibfSupported: false, initialZoom: 10 }],
    ["SVN", { name: "Slovenia", ibfSupported: false, initialZoom: 10 }],
    ["SLB", { name: "Solomon Islands", ibfSupported: false, initialZoom: 10 }],
    ["SOM", { name: "Somalia", ibfSupported: false, initialZoom: 10 }],
    ["ZAF", { name: "South Africa", ibfSupported: false, initialZoom: 10 }],
    ["SSD", { name: "South Sudan", ibfSupported: false, initialZoom: 10 }],
    ["ESP", { name: "Spain", ibfSupported: false, initialZoom: 10 }],
    ["LKA", { name: "Sri Lanka", ibfSupported: false, initialZoom: 10 }],
    ["SDN", { name: "Sudan", ibfSupported: false, initialZoom: 10 }],
    ["SUR", { name: "Suriname", ibfSupported: false, initialZoom: 10 }],
    ["SWE", { name: "Sweden", ibfSupported: false, initialZoom: 10 }],
    ["CHE", { name: "Switzerland", ibfSupported: false, initialZoom: 10 }],
    ["SYR", { name: "Syria", ibfSupported: false, initialZoom: 10 }],
    ["TWN", { name: "Taiwan", ibfSupported: false, initialZoom: 10 }],
    ["TJK", { name: "Tajikistan", ibfSupported: false, initialZoom: 10 }],
    ["TZA", { name: "Tanzania", ibfSupported: true, initialZoom: 10 }],
    ["THA", { name: "Thailand", ibfSupported: false, initialZoom: 10 }],
    ["TLS", { name: "Timor-Leste", ibfSupported: false, initialZoom: 10 }],
    ["TGO", { name: "Togo", ibfSupported: false, initialZoom: 10 }],
    ["TON", { name: "Tonga", ibfSupported: false, initialZoom: 10 }],
    ["TTO", { name: "Trinidad and Tobago", ibfSupported: false, initialZoom: 10 }],
    ["TUN", { name: "Tunisia", ibfSupported: false, initialZoom: 10 }],
    ["TUR", { name: "Turkey", ibfSupported: false, initialZoom: 10 }],
    ["TKM", { name: "Turkmenistan", ibfSupported: false, initialZoom: 10 }],
    ["TUV", { name: "Tuvalu", ibfSupported: false, initialZoom: 10 }],
    ["UGA", { name: "Uganda", ibfSupported: true, initialZoom: 10 }],
    ["UKR", { name: "Ukraine", ibfSupported: false, initialZoom: 10 }],
    ["ARE", { name: "United Arab Emirates", ibfSupported: false, initialZoom: 10 }],
    ["GBR", { name: "United Kingdom", ibfSupported: false, initialZoom: 10 }],
    ["USA", { name: "United States", ibfSupported: false, initialZoom: 10 }],
    ["URY", { name: "Uruguay", ibfSupported: false, initialZoom: 10 }],
    ["UZB", { name: "Uzbekistan", ibfSupported: false, initialZoom: 10 }],
    ["VUT", { name: "Vanuatu", ibfSupported: false, initialZoom: 10 }],
    ["VAT", { name: "Vatican City", ibfSupported: false, initialZoom: 10 }],
    ["VEN", { name: "Venezuela", ibfSupported: false, initialZoom: 10 }],
    ["VNM", { name: "Vietnam", ibfSupported: false, initialZoom: 10 }],
    ["YEM", { name: "Yemen", ibfSupported: false, initialZoom: 10 }],
    ["ZMB", { name: "Zambia", ibfSupported: false, initialZoom: 10 }],
    ["ZWE", { name: "Zimbabwe", ibfSupported: false, initialZoom: 10 }],
]);